### ISSUE TITLE
[error] workflow error,

### ISSUE THREAD

**Issue by behoney** [behoney/behoney.github.io#1]
```
Run npm run build

> behoney-gp@ build /home/runner/work/behoney.github.io/behoney.github.io
> next build

error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error

> Build error occurred
Error: Not supported
    at Object.loadConfig [as default] (/home/runner/work/behoney.github.io/behoney.github.io/node_modules/next/dist/server/config.js:399:74)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! behoney-gp@ build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the behoney-gp@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-01-01T18_04_21_734Z-debug.log
Error: Process completed with exit code 1.
```

https://github.com/behoney/behoney.github.io/runs/4680432964?check_suite_focus=true#step:6:23

**Comment by behoney** [comment]
# [next.config.js Loading Error](https://nextjs.org/docs/messages/next-config-error)

Why This Error Occurred
When attempting to load your next.config.js or next.config.mjs file, an error occurred. This could be due to a syntax error or attempting to require/import a module that wasn't available.

Possible Ways to Fix It
See the error message in your terminal where you started next to see more context.

Note: This config file is not transpiled by Next.js, so only use features supported by your current Node.js version.



---


will check [`next.config.js`](https://github.com/behoney/behoney.github.io/blob/main/next.config.js)
```
const withMDX = require("@next/mdx")({
  extension: /\.mdx?$/,
});
module.exports = withMDX({
  pageExtensions: ["js", "jsx", "mdx"],
  target: "serverless",
  reactStrictMode: true,
});
```

**Comment by behoney** [comment]
handling on the branch,

https://github.com/behoney/behoney.github.io/tree/build_issue%231

firstly, there's no `npm run export` command on `package.json`
 
so I added it, and have tested.



```



  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "export": "next export",
    "deploy": "npm run build"
  },


```

**Comment by behoney** [comment]
![image](https://user-images.githubusercontent.com/9066602/147904382-e0462de9-7fd7-4c0d-aacb-2e40d697e093.png)

`next.config.js` occur issue again for `next build`,,, why?


---
the local env runs well


```

PS C:\Users\bhoney\behoney-gp> npm run export

> export
> next export

warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
info  - using build directory: C:\Users\bhoney\behoney-gp\.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "C:\Users\bhoney\behoney-gp\next.config.js". Generating map from "./pages"
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at C:\Users\bhoney\behoney-gp\node_modules\next\dist\export\index.js:256:23
    at async Span.traceAsyncFn (C:\Users\bhoney\behoney-gp\node_modules\next\dist\trace\trace.js:74:20)
PS C:\Users\bhoney\behoney-gp> npm run build

> build
> next build

warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
info  - Checking validity of types
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (3/3)
info  - Finalizing page optimization

Page                                       Size     First Load JS
┌ ● /                                      3.1 kB         74.6 kB
├   └ css/b282b959608f58d4.css             718 B
├   /_app                                  0 B            71.5 kB
├ ○ /404                                   194 B          71.7 kB
├ λ /api/getPostsData                      0 B            71.5 kB
└ λ /api/hello                             0 B            71.5 kB
+ First Load JS shared by all              71.5 kB
  ├ chunks/framework-6e4ba497ae0c8a3f.js   42 kB
  ├ chunks/main-deb592798b94b511.js        28.2 kB
  ├ chunks/pages/_app-9cd1d19dd7237c4c.js  493 B
  ├ chunks/webpack-514908bffb652963.js     770 B
  └ css/2974ebc8daa97b04.css               209 B

λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)



```

**Comment by behoney** [comment]
## passed yarn export

`next/image` is an evil, i removed all `import image form next/image` according to [this](https://github.com/vercel/next.js/issues/18356#issuecomment-919750076)

**Comment by behoney** [comment]
# solution
all are about dev env.

![image](https://user-images.githubusercontent.com/9066602/147906040-c1e0409c-0722-44af-a038-59ee94a43cd9.png)

dev env updated with this [commit ](https://github.com/behoney/behoney.github.io/commit/334e57f478277de3a7acb63219ed6dd5d0f7e81e) and I merged
